movie/urls.py
from django.urls import path

from movie.views import (
    MovieListView,
    MovieDetailView,
    SearchResultsView,
    FavoritesView,
    AddMovieView,
    DeleteMovieView,
    UpdateMovieView,
    ToggleFavoriteView,
    AddCommentView,
    MostLikedMoviesView,
    NewestMoviesView,
    GenreMoviesView,
)

app_name = 'movies'

urlpatterns = [
    path('', MovieListView.as_view(), name='movie_list'),
    path('<int:pk>/', MovieDetailView.as_view(), name='movie_detail'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('favorites/', FavoritesView.as_view(), name='favorite_movies'),
    path('add/', AddMovieView.as_view(), name='add_movie'),
    path('movie/<int:pk>/delete/', DeleteMovieView.as_view(), name='delete_movie'),
    path('movie/<int:pk>/update/', UpdateMovieView.as_view(), name='update_movie'),
    path('movie/<int:pk>/add_comment/', AddCommentView.as_view(), name='add_comment'),
    path('toggle_favorite/<int:movie_id>/', ToggleFavoriteView.as_view(), name='toggle_favorite'),
    path('liked/', MostLikedMoviesView.as_view(), name='movie_liked'),
    path('newest/', NewestMoviesView.as_view(), name='movie_newest'),
    path('genres/', GenreMoviesView.as_view(), name='movie_genres'),
]

movieAppNew/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('movie/', include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import LoginView, RegisterView, logout_view, home_view, ProfileView

urlpatterns = [
    path('', home_view, name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', logout_view, name='logout'),
]

templates/base/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie Database</title>
    <!-- Add your stylesheets and other meta tags here -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>

        /* Add custom CSS styles here */
        .body {
            background-image: url('{% static 'images/movie-yellow-background.jpg' %}');
            background-size: cover;
            background-position: center;
            padding: 20px; /* Adjust padding as needed */
        }

        /* Add any additional styling for the content */
        .content-container {
            padding: 20px; /* Add padding as needed */
        }
    </style>
</head>
<body class="body">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'movies:movie_list' %}"><h1>MOVIES DATABASE</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movies:add_movie' %}">Add Movie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movies:movie_list' %}">Movie List <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movies:favorite_movies' %}">Favorites</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Movie Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'movies:movie_liked' %}">Most Liked</a>
                        <a class="dropdown-item" href="{% url 'movies:movie_newest' %}">Newest</a>
                        <a class="dropdown-item" href="{% url 'movies:movie_genres' %}">Genres</a>
                    </div>
                </li>
                <p class="nav-link">Welcome, {{ user.username }}! (<a href="{% url 'logout' %}">Logout</a>)</p>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<main>
    {% block content %}

    {% endblock %}
</main>

<footer class="footer mt-5">
    <div class="container">
        <p class="text-center text-muted">
            <strong style="color: black">&copy; 2023 Your Movie Database. All rights reserved.</strong> |
            <a href="{# Add your privacy policy link here #}">Privacy Policy</a> |
            <a href="{# Add your terms of service link here #}">Terms of Service</a>
        </p>
    </div>
</footer>


<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<!-- Add your scripts here -->
</body>
</html>