movie/urls.py
from django.urls import path

from movie.views import (
    MovieListView,
    MovieDetailView,
    SearchResultsView,
    FavoritesView,
    AddMovieView,
    DeleteMovieView,
    UpdateMovieView,
    ToggleFavoriteView,
    AddCommentView,
    MostLikedMoviesView,
    NewestMoviesView,
    GenreMoviesView,
)

app_name = 'movies'

urlpatterns = [
    path('', MovieListView.as_view(), name='movie_list'),
    path('<int:pk>/', MovieDetailView.as_view(), name='movie_detail'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('favorites/', FavoritesView.as_view(), name='favorite_movies'),
    path('add/', AddMovieView.as_view(), name='add_movie'),
    path('movie/<int:pk>/delete/', DeleteMovieView.as_view(), name='delete_movie'),
    path('movie/<int:pk>/update/', UpdateMovieView.as_view(), name='update_movie'),
    path('movie/<int:pk>/add_comment/', AddCommentView.as_view(), name='add_comment'),
    path('toggle_favorite/<int:movie_id>/', ToggleFavoriteView.as_view(), name='toggle_favorite'),
    path('liked/', MostLikedMoviesView.as_view(), name='movie_liked'),
    path('newest/', NewestMoviesView.as_view(), name='movie_newest'),
    path('genres/', GenreMoviesView.as_view(), name='movie_genres'),
]

movieAppNew/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('movie/', include('movie.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user.views import LoginView, RegisterView, logout_view, home_view, ProfileView

urlpatterns = [
    path('', home_view, name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', logout_view, name='logout'),
]

templates/add_comment.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <h1 style="color: aqua">Add Comment</h1>
    <h2 style="color: aqua">Movie: {{ movie.title }}</h2>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <a href="{% url 'movies:movie_detail' pk=movie.pk %}">Back to Movie Details</a>
{% endblock %}

templates/add_movie.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                {% if user.is_authenticated %}
                    <h1 class="mb-4">ADD NEW MOVIE</h1>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                {% else %}
                    <p class="mt-4">You must be logged in to add a new movie. (<a href="{% url 'login' %}">Login</a>)</p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

templates/favorite_movies.html
{% extends 'base/_base.html' %}

{% block content %}
    <h1>YOUR FAVORITE MOVIES</h1>

    <div class="container">
        <div class="row">
            {% if favorite_movies %}
                {% for movie in favorite_movies %}
                    <a href="{% url 'movies:movie_detail' movie.id %}" class="col-md-4 mb-4 movie-card">
                        <div class="card movie-card-container">
                            <div class="card-body" style="text-align: center">
                                <h5 class="card-title">{{ movie.title }}</h5>
                                <p class="card-text">{{ movie.description }}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <div class="col-md-12">
                    <h3 style="text-align: center; color: aqua">You haven't marked any movies as favorites yet.</h3>
                </div>
            {% endif %}
        </div>
    </div>

    <style>
        .movie-card {
            text-decoration: none;
            color: inherit;
            transition: transform 0.3s;
        }

        .movie-card:hover {
            transform: scale(1.05);
        }

        .movie-card-container {
            margin-bottom: 20px;
        }
    </style>

{% endblock %}

templates/home.html
{% extends 'base/_base.html' %}

{% block title %}
    <title class="custom-title">Home - Movie Database</title>
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h1 class="white">Welcome to the Movie Database!</h1>
        <h1 class="p-white">Explore our collection of movies and enjoy your stay.</h1>
    </div>
{% endblock %}

templates/middleware.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Permission Denied</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            color: #333;
            margin: 0;
            padding: 0;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        .container {
            text-align: center;
        }

        h1 {
            color: #d9534f;
        }

        p {
            font-size: 18px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Permission Denied</h1>
        <p>{{ error_message }}</p>
    </div>
</body>
</html>

templates/movie_details.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    
    {% if messages %}
        <ul style="color: white" class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <div class="movie-container" style="color: white">
        <h1 class="movie-title" style="color: black; font-size: 50px">{{ movie.title }}</h1>
        <div class="movie-details" style="text-align: left; color: black; font-size: 36px">
            <p><strong>Description:</strong> {{ movie.description }}</p>
            <p><strong>Release Date:</strong> {{ movie.release_date }}</p>
            <p><strong>Director:</strong> {{ movie.director }}</p>
            <p><strong>Genre:</strong> {{ movie.genre }}</p>
            {% if movie.cover_image %}
                <p><strong>Image:</strong></p>
                <img src="{{ movie.cover_image.url }}">
            {% else %}
                <p>No cover image available</p>
            {% endif %}
        </div>

        <div class="btn-group d-flex justify-content-center" style="margin: 10px">
            <form method="post" action="{% url 'movies:update_movie' pk=movie.id %}">
                {% csrf_token %}
                {% if user == movie.user %}
                    <input type="submit" value="Update" class="btn btn-primary">
                {% endif %}
            </form>

            <form method="post" action="{% url 'movies:delete_movie' pk=movie.id %}">
                {% csrf_token %}
                {% if user == movie.user %}
                    <input type="hidden" name="next" value="{% url 'movies:movie_list' %}">
                    <input type="submit" value="Delete" class="btn btn-danger">
                {% endif %}
            </form>

            <button id="toggleFavoriteBtn" class="btn btn-warning">Toggle Favorite</button>
        </div>


        {#        <h2 style="color: black">User Ratings</h2>#}
        {#        {% for rating in movie.ratings.all %}#}
        {#            <p style="color: black">{{ rating.user.username }} - {{ rating.value }}</p>#}
        {#        {% endfor %}#}
        <h2 style="color: black">Average Rating</h2>
        <p style="color: black">{{ movie.average_rating|floatformat:2 }}</p>

        <h2 style="color: black">Rate this Movie</h2>
        <p style="color: black">1 - 10</p>
        <form method="post" action="{% url 'movies:movie_detail' movie.id %}">
            {% csrf_token %}
            {{ rating_form|crispy }}
            <button type="submit" class="btn btn-primary">Submit Rating</button>
        </form>


        <h3 style="color: black">Comments</h3>
        {% for comment in comments %}
            <p style="color: black">{{ comment.text }} - {{ comment.user.username }} ({{ comment.created_at }})</p>
        {% endfor %}

        <!-- Comment form -->
        <form method="post" action="{% url 'movies:add_comment' movie.id %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <button type="submit" class="btn btn-primary">Add Comment</button>
        </form>

        {% if user.is_authenticated %}
            <script>
                document.getElementById('toggleFavoriteBtn').addEventListener('click', function () {
                    // Send a POST request to toggle_favorite endpoint
                    fetch('{% url "movies:toggle_favorite" movie.id %}', {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}',
                            'Content-Type': 'application/json',
                        },
                        body: JSON.stringify({}),
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.status === 'success') {
                                // Update UI or provide feedback
                                alert('Favorite status toggled!');
                            } else {
                                alert('Failed to toggle favorite status.');
                            }
                        });
                });
            </script>
        {% endif %}
    </div>
{% endblock %}

templates/movie_genres.html
{% extends 'base/_base.html' %}

{% block content %}

    <h2 style="text-align: center; color: aqua">Genres</h2>
    <div class="container">
        {% for genre, movies in genre_movies.items %}
            <div class="mb-4">
                <h3 style="text-align: center; color: aqua">{{ genre }}</h3>
                <div class="row">
                    {% for movie in movies %}
                        <a href="{% url 'movies:movie_detail' movie.id %}" class="col-md-4 mb-3 movie-card">
                            <div class="card">
                                <div class="card-body" style="text-align: center">
                                    <h5 class="card-title">{{ movie.title }}</h5>
                                    <p class="card-title">{{ movie.description }}</p>
                                </div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
    </div>

    <style>
        .movie-card {
            text-decoration: none;
            color: inherit;
            transition: transform 0.3s;
        }

        .movie-card:hover {
            transform: scale(1.05);
        }
    </style>

{% endblock %}

templates/movie_liked.html
{% extends 'base/_base.html' %}

{% block content %}

    <h2 style="text-align: center; color: aqua">Most Liked Movies</h2>
    <div class="container">
        <div class="row">
            {% for movie in most_liked_movies %}
                <a href="{% url 'movies:movie_detail' movie.id %}" class="col-md-4 mb-4 movie-card">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title" style="text-align: center">{{ movie.title }}</h5>
                            <p class="card-title" style="text-align: center">{{ movie.description }}</p>
                            <p class="card-text" style="text-align: center">Average Rating:
                                {{ movie.average_rating|floatformat:2 }}</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

    <style>
        .movie-card {
            text-decoration: none;
            color: inherit;
            transition: transform 0.3s;
        }

        .movie-card:hover {
            transform: scale(1.05);
        }
    </style>

{% endblock %}

templates/movie_list.html
{% extends 'base/_base.html' %}
{% load static %}

{% block content %}
    <h1>MOVIE LIST </h1>

    {% if messages %}
        <ul style="color: white" class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <div class="search-form-container" style="text-align: right; margin-bottom: 20px;">
        <!-- Add dropdown for filtering by genre -->
        <form class="filter-form" method="get" action="{% url 'movies:movie_list' %}">
            <select name="genre" id="genre" onchange="this.form.submit()">
                <option value="" {% if not request.GET.genre %}selected{% endif %}>All</option>
                {% for genre_choice in genre_choices %}
                    <option value="{{ genre_choice.0 }}"
                            {% if request.GET.genre == genre_choice.0 %}selected{% endif %}>
                        {{ genre_choice.1 }}
                    </option>
                {% endfor %}
            </select>
        </form>

        <form class="search-form" method="get" action="{% url 'movies:search_results' %}">
            <div class="input-group">
                <input type="text" id="search" name="q" placeholder="Search movies" class="form-control">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>

    <div class="container">
        <div class="row">
            {% for movie in movies %}
                <a href="{% url 'movies:movie_detail' movie.id %}" class="col-md-4 mb-4 movie-card">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title" style="text-align: center">{{ movie.title }}</h5>
                            <p class="card-text" style="text-align: center">{{ movie.description }}</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

    <style>

        .search-form-container {
            text-align: right;
            margin-bottom: 20px;
        }

        .search-form-container {
            text-align: right;
            margin-bottom: 20px;
        }

        .filter-form,
        .search-form {
            display: inline-block;
            margin-right: 10px;
        }

        .filter-form select,
        .search-form input {
            padding: 8px;
            font-size: 14px;
        }

        .filter-form select {
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        .search-form input {
            border: 1px solid #3498db;
            border-radius: 4px;
            margin-right: 5px;
        }

        .search-form button {
            padding: 8px 15px;
        }

        .movie-card {
            text-decoration: none;
            color: inherit;
            transition: transform 0.3s;
        }

        .movie-card:hover {
            transform: scale(1.05);
        }
    </style>

{% endblock %}

templates/movie_newest.html
{% extends 'base/_base.html' %}

{% block content %}

    <h2 style="text-align: center; color: aqua">Newest Movies</h2>
    <div class="container">
        <div class="row">
            {% for movie in newest_movies %}
                <a href="{% url 'movies:movie_detail' movie.id %}" class="col-md-4 mb-4 movie-card">
                    <div class="card">
                        <div class="card-body" style="text-align: center">
                            <h5 class="card-title">{{ movie.title }}</h5>
                            <h5 class="card-title">{{ movie.description }}</h5>
                            <p class="card-text">Release Date: {{ movie.release_date }}</p>
                            <!-- Add other movie details as needed -->
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>

    <style>
        .movie-card {
            text-decoration: none;
            color: inherit;
            transition: transform 0.3s;
        }

        .movie-card:hover {
            transform: scale(1.05);
        }
    </style>

{% endblock %}

templates/search_results.html
{% extends 'base/_base.html' %}

{% block content %}
    <h2 style="text-align: center; color: aqua">Search Results for "{{ query }}"</h2>
    <div class="container">
        <div class="row">
            {% if movies %}
                {% for movie in movies %}
                    <a href="{% url 'movies:movie_detail' movie.id %}" class="col-md-4 mb-4 movie-card">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title" style="text-align: center">{{ movie.title }}</h5>
                                <p class="card-title" style="text-align: center">{{ movie.description }}</p>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            {% else %}
                <h2 style="text-align: center; color: aqua">{{ message }}</h2>
            {% endif %}
        </div>
    </div>

    <style>
        .movie-card {
            text-decoration: none;
            color: inherit;
            transition: transform 0.3s;
        }

        .movie-card:hover {
            transform: scale(1.05);
        }
    </style>
{% endblock %}

templates/update_movie.html
{% extends 'base/_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <h1>UPDATE MOVIE</h1>
                    <h2 style="text-align: center; color: aqua"><strong>{{ movie.title }}</strong></h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    {% else %}
                    <a href="{% url 'login' %}"></a>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}